version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: pozarnik/yamdb_d:latest
    restart: always
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/
      - ./media:/var/html/media/
    depends_on:
      - web

volumes:
  db_value:
